### PR TITLE
Solved #23 Submenu stays open if not clicked and closed manually

### PR DESCRIPTION
**Pull request by shreysachani**
Issue Solved. Managed the states, didn't create any hooks 

https://github.com/user-attachments/assets/e0ca0e2e-9994-4d88-b02b-e2b117ed2b66

### CODE REVIEW

**Comment by Chetan-KK** [comment]
please star this repo

**Comment by Chetan-KK** [comment]
can you make this change on other branch than main

**Comment by shreysachani** [comment]
Yes sure. Do you mean on one of your existing branches other than main or shall I create a new branch and make a pull request.???

**Comment by Chetan-KK** [comment]
create your own new branch on your fork and make a pull request from their

**Comment by shreysachani** [comment]
Ok will do now

**Pull request merged**
