### PR TITLE
added notification and calander component to the taskbar

### PR DESCRIPTION
**Pull request by 2021eo3ar**
I have added a notificatin and calander component to the taskbar, and both can be modified as per the need of the project

### CODE REVIEW

**Comment by 2021eo3ar** [comment]
@Chetan-KK please have a look at this PR and merge it, and also tell me if you any modifications in it, I will add those changes too.

**Comment by 2021eo3ar** [comment]
Hey @Chetan-KK kindly merge my branch if this meets to your expectation

**Comment by Chetan-KK** [comment]
done

**Comment by 2021eo3ar** [comment]
Thankyou so much for merging my branch, if there is anything I can help you with kindly tell me, And will you please add the hacktoberfest label to my branch

**Comment by Chetan-KK** [comment]
you can see issues section

**Comment by Chetan-KK** [comment]
hi @2021eo3ar can you please star this repo

**Comment by 2021eo3ar** [comment]
On my pc

**Comment by Chetan-KK** [comment]
star*

**Pull request merged**
