### PR TITLE
Fixex #2 All the Power Buttons are Working now

### PR DESCRIPTION
**Pull request by FurrukhJamal**
I have implemented all the features of the power buttons, on sleep the screen goes to black and turns back to the window screen on movement of mouse or a keypress. Have added a Loading animation simulating windows getting started. Also have fixed the start menu feature. It was not closing when clicks were made somewhere else on the screen. In implementing all these features I had lift up the state to the root `App.jsx` and passed the required states for components using `useContext`. As this app grows there might come a need for using a state management library like redux. Have also written all the tests for the screens I could think of

here are the mentioned features that I have made in a video format 
[https://youtu.be/L77fJteRnYM](url)

### CODE REVIEW

**Comment by Chetan-KK** [comment]
it's working fine but their are some changes - 

- add https://uiverse.io/SelfMadeSystem/black-yak-68 this animation while restarting ,shutting down and sleeping
- add instruction after sleep so users can understand to move mouse for starting windows
- after user click outside of start menu all their inner menus should be close
menu
- screen is being black frequently, without clicking any button
- after sleep load and wait, after moving mouse it's starting immediately

other thing are very good!! keep it up!

**Comment by FurrukhJamal** [comment]
1. This animation is very complex, I spent a few hours in trying to get it to working for react but couldnt do it. Is there a way I can get these converted to React specific? I am afraid I am not that good with css, thats why I switched to other spinners
2. Wouldn't providing instructions on sleep to users negate the whole point of the project been a clone? I mean when we click sleep on our windows we dont see any instructions
3. I'll see what I can do for this
4. I dont understand this point, can you explain a bit
5. In our own windows I think the screen comes back immediately so thats what my approch was to achieve, but I can implement a delay for that, it wouldnt be hard

**Comment by Chetan-KK** [comment]
1. just copy whole css in css file and html in jsx, it's not much complex, try it
2. yes but we have to consider user experiance also, it's just for user experience

4. 
this is how screen is being black

https://github.com/Chetan-KK/Windows-10-Clone/assets/44507196/bbef819f-33c4-42a4-9f07-e219d65e22d0

5. we have to add dealy because of this issue:-

https://github.com/Chetan-KK/Windows-10-Clone/assets/44507196/e57777f0-1003-4126-a6fb-d98f3d56d1c3

**Comment by FurrukhJamal** [comment]
I have tried working with the animation you've given converted it to react still its not functioning as desired, and I just can't seem to figure out what the problem is. I have left all the css and the converted styles in `Loading.jsx` in the function `TestLoading` may be someone else can fix that issue.
Fixed the screen getting black issue as well as the inner menus getting closed. I would still suggest to keep the sleep functionality as it is cuz changing that would loose the essence of this been a windows clone. Think abt it, try clicking sleep on your windows of your pc, this is exactly what happens when one clicks sleep on the real windows. If you disagree let me know then I would add the delay as well, would hardly take 3 or 4 lines of code

**Comment by Chetan-KK** [comment]
see the video i've sent, we have to add dealy because our pc doesn't wake up in after we move mouse or click any key, their is some dealy.

**Comment by FurrukhJamal** [comment]
so you want a delay after the sleep button is clicked or in waking up after mouse is moved or a key is pressed?

**Comment by Chetan-KK** [comment]
after sleep wait for around 250ms before listening any events

**Comment by FurrukhJamal** [comment]
Done, 250 seemed a very small delay I thought you might have meant 2500, just check the functionality if you are satisfied otherwise I can change it to 250 too, just let me know

**Comment by Chetan-KK** [comment]
it looks awesome!! thanks for your contribution!

**Pull request merged**
